# Generated by Django 4.2.16 on 2024-11-21 18:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('choose', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='VoteOpt',
        ),
    ]
