# Generated by Django 4.2.16 on 2024-11-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0002_content_users_rename_voted_at_vote_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
