# Generated by Django 4.2.16 on 2024-11-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0004_alter_poll_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
