# Generated by Django 5.1.7 on 2025-03-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0005_content_category_contentoption_contentoptionvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.RemoveField(
            model_name='contentoption',
            name='votes_count',
        ),
        migrations.AddField(
            model_name='content',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
