# Generated by Django 5.1.4 on 2025-05-02 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0006_remove_content_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='private_key_encrypted',
            field=models.TextField(blank=True, help_text='PEM приватного ключа, зашифрованный MASTER_KEY'),
        ),
        migrations.AddField(
            model_name='content',
            name='public_key',
            field=models.TextField(blank=True, help_text='PEM публичного ключа'),
        ),
        migrations.CreateModel(
            name='EncryptedVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_choice', models.TextField()),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_votes', to='choose.content')),
            ],
        ),
    ]
