# Generated by Django 5.1.4 on 2025-05-03 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0007_content_private_key_encrypted_content_public_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='choose.content')),
            ],
            options={
                'unique_together': {('content', 'option_text')},
            },
        ),
    ]
