# Generated by Django 5.1.4 on 2025-05-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0008_pollresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedvote',
            name='pvid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='encryptedvote',
            unique_together={('content', 'pvid')},
        ),
    ]
